### ISSUE TITLE
How to visualize Emergent behavior?

### ISSUE THREAD

**Issue by fokx** [alirezakazemipour/DIAYN-PyTorch#1]

**Comment by akazemipour** [comment]
Hi,
Could you please provide more information about your question? Specifically, do you want to know how to render the agent while performing emergent behavior at the training time or test?

**Comment by fokx** [comment]
Yes, I'd like to know how the emergent behavior animations shown in README.md are generated.

**Comment by akazemipour** [comment]
Those animations are representing agents' performance during test time, therefore, I followed the following procedure to obtain such animations:

After training the agent, I found which learned skills were meaningful through my TensorBoard logs so, I tested the agent for all skills and recorded his behavior for all of them but only kept the meaningful ones in the end. 

To produce animations, the key part was to use `mode='rgb_array'` in the `render` function of OpenAI gym API so I could produce .mp4 videos via OpenCV's `VideoWriter` class. At the end [ezgif.com](https://ezgif.com/maker) produced gif files of my previously generated .mp4 videos.

Please take a look at:
https://github.com/alirezakazemipour/DIAYN-PyTorch/blob/main/Common/play.py

**Comment by fokx** [comment]
OK, that makes sense. Thank you.
